from io import StringIO

from django.test import TestCase, override_settings
from django.urls import reverse
from django.core.cache import cache
from django.core.management import call_command
from rest_framework.test import APIClient
from rest_framework import status

from .models import (
    CustomUser, Profile, TechStack, Tech_Section, Project,
    Education, Certificate, Profession, SocialLink, Service, Testimonial, ContactMessage,
)
from .serializers import (
    ProfileSerializer, EducationSerializer, CertificateSerializer, ProfessionSerializer,
    ProjectSerializer, SocialLinkSerializer, ServiceSerializer, TestimonialSerializer,
    ResumeSerializer, ContactMessageSerializer,
)
from portfolio.templatetags.cloudinary_filters import optimized
from django.contrib import admin


def _make_superuser(**kwargs):
    defaults = dict(email='admin@example.com', password='testpassword', is_superuser=True)
    defaults.update(kwargs)
    return CustomUser.objects.create_user(**defaults)


class PortfolioTestCase(TestCase):
    def setUp(self):
        self.client = APIClient()
        self.user = _make_superuser()
        self.section = Tech_Section.objects.create(name='Backend')
        self.tech = TechStack.objects.create(name='Python', section=self.section)
        self.profile = Profile.objects.create(
            user=self.user,
            name='Test User',
            title='Test Title',
            bio='Test Bio',
            address='Test Address',
            phone='1234567890',
            philosophy='Test Philosophy',
        )
        self.profile.technologies.add(self.tech)
        self.project = Project.objects.create(
            user=self.user,
            title='Test Project',
            description='Test Description',
            motive='Test Motive',
            problem_statement='Test Problem',
            impact='Increased test coverage by 100%',
            architecture_notes='Uses Django and REST Framework',
        )
        self.project.technologies.add(self.tech)

    def test_portfolio_data_api(self):
        """Test the public API endpoint that gathers all portfolio data."""
        url = reverse('portfolio-data')
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data['profile']['name'], 'Test User')
        self.assertEqual(response.data['profile']['philosophy'], 'Test Philosophy')
        self.assertEqual(len(response.data['tech_stack']), 1)
        self.assertEqual(response.data['tech_stack'][0]['name'], 'Python')
        self.assertEqual(len(response.data['profile_tech_stack']), 1)
        self.assertEqual(response.data['projects'][0]['impact'], 'Increased test coverage by 100%')

    def test_contact_message_submission(self):
        """Test anonymous submission of contact messages."""
        url = '/api/contact/'
        data = {
            'sender_name': 'Inquirer',
            'sender_email': 'inquirer@example.com',
            'subject': 'Inquiry',
            'message': 'Hello, I am interested in your work.',
            'website': ''  # honeypot field
        }
        response = self.client.post(url, data)
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(ContactMessage.objects.filter(sender_name='Inquirer').count(), 1)

    def test_contact_message_honeypot_rejection(self):
        """Test that honeypot field rejects spam."""
        url = '/api/contact/'
        data = {
            'sender_name': 'Spammer',
            'sender_email': 'spammer@example.com',
            'subject': 'Spam',
            'message': 'Buy my stuff',
            'website': 'filled by bot'  # honeypot triggered
        }
        response = self.client.post(url, data)
        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)

    def test_protected_dashboard_access(self):
        """Test that the dashboard is protected from non-superusers."""
        url = reverse('dashboard')
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_302_FOUND)

        regular_user = CustomUser.objects.create_user(
            email='regular@example.com', password='testpassword',
        )
        self.client.force_login(regular_user)
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_302_FOUND)

        self.client.force_login(self.user)
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)


class ModelTests(TestCase):
    def test_tech_section_slug_autogenerated(self):
        section = Tech_Section.objects.create(name='Front End')
        self.assertEqual(section.slug, 'front-end')

    def test_techstack_unique_per_section(self):
        section = Tech_Section.objects.create(name='Section')
        TechStack.objects.create(name='Dup', section=section)
        with self.assertRaises(Exception):
            TechStack.objects.create(name='Dup', section=section)

    def test_profile_optional_phone_address(self):
        user = CustomUser.objects.create_user(email='p@example.com', password='x')
        profile = Profile.objects.create(user=user, name='No Contact')
        profile.refresh_from_db()
        self.assertIsNone(profile.phone)
        self.assertIsNone(profile.address)


class ViewTests(TestCase):
    def setUp(self):
        cache.clear()
        self.user = _make_superuser()
        self.profile = Profile.objects.create(
            user=self.user, name='Test User', title='Dev',
            bio='</script><script>alert(1)</script>',
        )

    def test_home_page_renders(self):
        response = self.client.get('/')
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.context['profile'].name, 'Test User')
        self.assertIn('json_ld', response.context)

    def test_json_ld_is_script_safe(self):
        """Bio with </script> must not break out of the JSON-LD block."""
        response = self.client.get('/')
        content = response.content.decode()
        self.assertNotIn('</script><script>alert(1)</script>', content)
        self.assertIn('\\u003c/script\\u003e', content)

    def test_portfolio_data_404_when_no_superuser(self):
        CustomUser.objects.filter(is_superuser=True).delete()
        response = self.client.get(reverse('portfolio-data'))
        self.assertEqual(response.status_code, status.HTTP_404_NOT_FOUND)

    def test_health_check_ok(self):
        response = self.client.get('/healthz/')
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data['status'], 'ok')


class SecurityHeaderTests(TestCase):
    def setUp(self):
        cache.clear()

    @override_settings(
        DEBUG=False, SECURE_SSL_REDIRECT=True, ALLOWED_HOSTS=['testserver'],
        SECURE_PROXY_SSL_HEADER=('HTTP_X_FORWARDED_PROTO', 'https'),
    )
    def test_ssl_redirect_active(self):
        response = self.client.get('/')
        self.assertEqual(response.status_code, status.HTTP_301_MOVED_PERMANENTLY)
        self.assertTrue(response['Location'].startswith('https://'))

    @override_settings(
        DEBUG=False, SECURE_SSL_REDIRECT=False, ALLOWED_HOSTS=['testserver'],
        SECURE_CONTENT_TYPE_NOSNIFF=True, SECURE_HSTS_SECONDS=3600,
        SECURE_HSTS_INCLUDE_SUBDOMAINS=True, SECURE_HSTS_PRELOAD=True,
        X_FRAME_OPTIONS='DENY',
    )
    def test_security_headers_present(self):
        response = self.client.get('/healthz/')
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response['X-Content-Type-Options'], 'nosniff')
        self.assertEqual(response['X-Frame-Options'], 'DENY')

    @override_settings(DEBUG=False, ALLOWED_HOSTS=[])
    def test_disallowed_host_rejected(self):
        response = self.client.get('/', HTTP_HOST='evil.example.com')
        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)


class ApiBehaviorTests(TestCase):
    def setUp(self):
        self.client = APIClient()
        self.user = CustomUser.objects.create_user(
            email='owner@example.com', password='testpassword',
        )
        self.section = Tech_Section.objects.create(name='Backend')

    def test_profile_upsert_does_not_duplicate(self):
        self.client.force_authenticate(self.user)
        r1 = self.client.post('/api/profile/', {'name': 'First'}, format='json')
        self.assertEqual(r1.status_code, status.HTTP_200_OK)
        self.assertEqual(Profile.objects.filter(user=self.user).count(), 1)

        r2 = self.client.post('/api/profile/', {'name': 'Second'}, format='json')
        self.assertEqual(r2.status_code, status.HTTP_200_OK)
        self.assertEqual(Profile.objects.filter(user=self.user).count(), 1)
        self.assertEqual(Profile.objects.get(user=self.user).name, 'Second')

    def test_techstack_duplicate_returns_200(self):
        self.client.force_authenticate(self.user)
        r1 = self.client.post('/api/tech-stack/', {'name': 'Go', 'section': self.section.id}, format='json')
        self.assertEqual(r1.status_code, status.HTTP_201_CREATED)
        r2 = self.client.post('/api/tech-stack/', {'name': 'Go', 'section': self.section.id}, format='json')
        self.assertEqual(r2.status_code, status.HTTP_200_OK)


class SerializerTests(TestCase):
    def test_user_field_not_serialized(self):
        """No serializer should leak the internal user PK."""
        serializers = [
            ProfileSerializer, EducationSerializer, CertificateSerializer,
            ProfessionSerializer, ProjectSerializer, SocialLinkSerializer,
            ServiceSerializer, TestimonialSerializer, ResumeSerializer,
            ContactMessageSerializer,
        ]
        for serializer_class in serializers:
            self.assertNotIn('user', serializer_class.Meta.fields,
                             f'{serializer_class.__name__} exposes user PK')

    def test_contact_honeypot_validation(self):
        serializer = ContactMessageSerializer(data={
            'sender_name': 'X', 'sender_email': 'x@example.com',
            'subject': 'S', 'message': 'M', 'website': 'bot',
        })
        self.assertFalse(serializer.is_valid())
        self.assertIn('website', serializer.errors)


class TemplateFilterTests(TestCase):
    def test_optimized_inserts_transforms(self):
        url = 'https://res.cloudinary.com/demo/image/upload/v123/folder/a.jpg'
        self.assertEqual(
            optimized(url, 400),
            'https://res.cloudinary.com/demo/image/upload/f_auto,q_auto,c_limit,w_400/v123/folder/a.jpg',
        )

    def test_optimized_handles_empty(self):
        self.assertEqual(optimized(''), '')


class AdminRegistrationTests(TestCase):
    def test_missing_models_registered(self):
        from .models import Service as Svc, Testimonial as Tst, ContactMessage as CMsg
        for model in (Svc, Tst, CMsg):
            self.assertIn(model, admin.site._registry,
                         f'{model.__name__} not registered in admin')


class MigrationConsistencyTests(TestCase):
    def test_no_missing_migrations(self):
        out = StringIO()
        call_command('makemigrations', '--check', '--dry-run', stdout=out, stderr=out)
