# Generated by Django 5.2.9 on 2026-04-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_resume_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='philosophy',
            field=models.TextField(blank=True, help_text='Your engineering mindset and development approach'),
        ),
        migrations.AddField(
            model_name='project',
            name='architecture_notes',
            field=models.TextField(blank=True, help_text='Deep-dive into technical decisions and trade-offs'),
        ),
        migrations.AddField(
            model_name='project',
            name='impact',
            field=models.TextField(blank=True, help_text="Quantifiable results, e.g., 'Reduced load time by 30%'"),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('DevOps', 'DevOps'), ('Tools', 'Tools')], default='Backend', max_length=100),
        ),
    ]
