# Generated by Django 5.2.9 on 2026-04-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_profile_philosophy_project_architecture_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, help_text='Key achievements or relevant coursework', null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(blank=True, help_text='e.g. Computer Science', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='grade',
            field=models.CharField(blank=True, help_text='GPA or Percentage', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='description',
            field=models.TextField(blank=True, help_text='Key responsibilities and achievements', null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='description',
            field=models.TextField(blank=True, help_text='Key responsibilities and achievements', null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='course',
            field=models.CharField(help_text='e.g. Bachelor of Technology', max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='course_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
