# Generated by Django 5.2.9 on 2026-04-23 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_education_description_education_field_of_study_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Database', 'Database'), ('Data/AI', 'Data/AI'), ('Tools', 'Tools')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='skills/icons/')),
            ],
            options={
                'verbose_name': 'Skill Master',
                'verbose_name_plural': 'Skill Master',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Priority for display')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.skillmaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'skill__name'],
                'unique_together': {('user', 'skill')},
            },
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
