# Generated by Django 5.2.9 on 2026-05-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_skillmaster_userskill_delete_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSkill',
        ),
        migrations.DeleteModel(
            name='SkillMaster',
        ),
        migrations.RenameModel(
            old_name='Technology',
            new_name='TechStack',
        ),
        migrations.AddField(
            model_name='techstack',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='tech_stack/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='portfolio.techstack'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='portfolio.techstack'),
        ),
    ]
