# Generated by Django 5.2.9 on 2026-05-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_replace_skills_with_techstack'),
    ]

    operations = [
        migrations.AddField(
            model_name='techstack',
            name='section',
            field=models.IntegerField(choices=[(1, 'Programming'), (2, 'Frameworks'), (3, 'Databases'), (4, 'Tools'), (5, 'Others'), (6, 'API')], default=1),
        ),
    ]
