# Generated by Django 5.2.9 on 2026-05-20 09:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_techstack_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tech_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='profession',
            name='experience',
            field=models.CharField(choices=[('internship', 'Internship'), ('professional', 'Professional')], default='professional', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='techstack',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_section', to='portfolio.tech_section'),
        ),
        migrations.DeleteModel(
            name='Internship',
        ),
    ]
