# Generated by Django 5.2.9 on 2026-05-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_tech_section_profession_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='experience',
            field=models.CharField(choices=[('internship', 'Internship'), ('professional', 'Professional')], max_length=50),
        ),
    ]
