# Generated by Django 6.0.5 on 2026-05-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_remove_project_tech_stack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tech_section',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='techstack',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='techstack',
            unique_together={('name', 'section')},
        ),
    ]
