# Generated by Django 6.0.5 on 2026-05-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_remove_project_tech_stack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tech_section',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='techstack',
            options={'ordering': ['name']},
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='techstack',
                    unique_together={('name', 'section')},
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$ BEGIN
                            ALTER TABLE portfolio_techstack
                            ADD CONSTRAINT portfolio_techstack_name_section_id_540187a8_uniq
                            UNIQUE (name, section_id);
                        EXCEPTION WHEN duplicate_object THEN
                            NULL;
                        END $$;
                    """,
                    reverse_sql="ALTER TABLE portfolio_techstack DROP CONSTRAINT IF EXISTS portfolio_techstack_name_section_id_540187a8_uniq;",
                ),
            ],
        ),
    ]
