# Generated by Django 6.0.5 on 2026-07-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_alter_tech_section_options_alter_techstack_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('web_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tech_section',
            name='show_on_portfolio',
            field=models.BooleanField(default=True, help_text='Display this section on the public portfolio'),
        ),
    ]
