# Generated by Django 6.0.5 on 2026-07-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_client_tech_section_show_on_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currently_learning',
            field=models.TextField(blank=True, help_text="Short note on what you're currently learning", null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='now_building',
            field=models.TextField(blank=True, help_text="Short note on what you're currently building", null=True),
        ),
    ]
