# Generated by Django 6.0.5 on 2026-07-18 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_alter_profile_address_alter_profile_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
