# Generated by Django 5.2.9 on 2026-08-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_profession_start_date_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='start_date',
            field=models.DateField(),
        ),
    ]
